export const USER_SIGN_UP = 'USER_SIGN_UP'
export const USER_LOG_IN = 'USER_LOG_IN'
export const USER_LOG_OUT = 'USER_LOG_OUT'
export const USER_EDIT = 'USER_EDIT'
export const USER_DELETE = 'USER_DELETE'

export const TASK_CREATE = 'TASK_CREATE'
export const TASK_DELETE = 'TASK_DELETE'
export const TASK_EDIT = 'TASK_EDIT'
export const EDIT_MODE = 'EDIT_MODE'
